import room1 from "./assets/img/portfolio/stanza1.jpg"
import room2 from "./assets/img/portfolio/stanza2.jpg"
import room3 from "./assets/img/portfolio/stanza3.jpg"
import room4 from "./assets/img/portfolio/stanza4.jpg"





export let roomsData = [
    {
      "id": 1,
      "title" : "Alloggio 1" ,
      "roomType" : "Casa vacanza con cucina" , 
      "bedNumber" : "5 posti letto" ,
      "img" : room1 , 
      "video" : "https://www.youtube.com/embed/y4wQu8LmdaI" ,
      "description" : "L'alloggio, situato al piano terra della struttura, è una vera e propria casa vacanza di 30 metri quadrati, con 5 posti letto totali, zona pranzo con tavolo e 5 sedie, angolo cottura (dotato di forno elettrico e a microonde, frigorifero, stoviglie, posate, pentolame), TV, bagno con doccia e lavatrice. Il monolocale è completamente climatizzato per essere utilizzato tutto l'anno. I posti letto sono così distribuiti: letto matrimoniale (2 posti letto), divano letto apribile (2 posti letto), letto apribile (1 posto letto). Gli ospiti possono usufruire gratuitamente della piscina (vengono riservati un ombrellone e due lettini), della rete wi-fi e del posto auto. La colazione non è inclusa. La biancheria e gli asciugamani non sono inclusi, il servizio è opzionale a pagamento. Se acquistato vengono forniti: biancheria da bagno per ciascun ospite (telo bagno e asciugamani), biancheria completa da letto e kit cortesia bagno (bagnoschiuma, saponetta, carta igienica)." ,
      "iconsName" : ["letto","TV","Cucina","Frigorifero","Forno elettrico","Microonde","Tavolo per 5","Lavatrice","Doccia","Phon","Condizionatore","Termosifoni","Armadio","Wifi","Piscina","Parcheggio","Sport","Giardino","Per famiglie","Fuga romantica"] ,
      "iconsLink" :[
        "https://www.tenutaricco.it/site/assets/img/icon/postiletto-64.png" , 
        "https://www.tenutaricco.it/site/assets/img/icon/tv-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/cucina-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/frigorifero-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/fornoelettrico-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/microonde-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/tavolo-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/lavatrice-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/doccia-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/phon-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/condizionatore-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/riscaldamento-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/armadio-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/wifi-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/piscina-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/parcheggio-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/sport-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/giardino-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/famiglia-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/cuore-64.png" , ] ,
      "pictures" : {
         "picture1" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza1_1.jpg" ,
         "picture2" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza1_2.jpg" ,
         "picture3" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza1_3.jpg" ,
         "picture4" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza1_4.jpg" ,
         "picture5" :  "https://www.tenutaricco.it/site/assets/img/portfolio/stanza1_5.jpg" ,
         "picture6" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza1_6.jpg" ,
         "picture7" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza1_7.jpg" ,
         "picture8" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza1_8.jpg" ,
         "picture9" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza1_9.jpg" ,
      } ,
     },

    {
      "id": 2,
      "title" : "Alloggio 2" ,
      "roomType" : "Camera con bagno" , 
      "bedNumber" : "3 posti letto" ,
      "img" : room2 ,
      "video" : "https://www.youtube.com/embed/pdaOvtLsHR8" ,
      "description" : "Il nostro alloggio più intimo. E' situato al piano primo della struttura e vi si accede tramite una scala esterna. La camera, di 16 metri quadrati, può accogliere fino a tre persone, grazie al letto matrimoniale ed al divano letto aggiuntivo. A disposizione un comodo frigobar, la TV hd e un tavolinetto. Adiacente alla camera abbiamo il bagno con doccia. L'alloggio è completamente climatizzato per essere utilizzato tutto l'anno. Gli ospiti possono usufruire gratuitamente della piscina (vengono riservati un ombrellone e due lettini), della rete wi-fi e del posto auto. La colazione non è inclusa. La biancheria e gli asciugamani non sono inclusi, il servizio è opzionale a pagamento. Se acquistato vengono forniti: biancheria da bagno per ciascun ospite (telo bagno e asciugamani), biancheria completa da letto e kit cortesia bagno (bagnoschiuma, saponetta, carta igienica).",
      "pictures" : {
        "picture1" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza2_1.jpg" ,
        "picture2" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza2_2.jpg" ,
        "picture3" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza2_3.jpg" ,
        "picture4" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza2_4.jpg" ,
        "picture5" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza2_4.jpg" ,
        "picture6" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza2_6.jpg" ,
        "picture7" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza2_7.jpg" ,
        "picture8" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza2_8.jpg" ,
        "picture9" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza2_9.jpg" ,
        "picture10" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza2_10.jpg" ,
      } , 
      "iconsName" : ["letto","TV","Frigobar","Doccia","Phon","Condizionatore","Termosifoni","Armadio","Wifi","Piscina","Parcheggio","Sport","Giardino","Per famiglie","Fuga romantica"] ,
      "iconsLink" : [
         "https://www.tenutaricco.it/site/assets/img/icon/postiletto-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/tv-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/minibar-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/doccia-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/phon-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/condizionatore-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/riscaldamento-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/armadio-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/wifi-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/piscina-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/parcheggio-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/sport-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/giardino-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/famiglia-64.png" ,
         "https://www.tenutaricco.it/site/assets/img/icon/cuore-64.png" , 
       ] ,
    } , 

    {
      "id": 3,
      "title" : "Alloggio 3" ,
      "reservation" : "Stai prenotando l'alloggio 3" ,
      "roomType" : "Casa vacanza con cucina" , 
      "bedNumber" : "5 posti letto" ,
      "img" : room3 ,
      "video" : "https://www.youtube.com/embed/Ltmnc2fi4_0" ,
      "description" : "Questo è il nostro alloggio più spazioso. E' situato al piano primo della struttura e vi si accede tramite una scala esterna. E' una vera e propria casa vacanza di 45 metri quadrati, con 5 posti letto. Nell'ambiente principale troviamo un letto matrimoniale (2 posti letto), un divano letto apribile (2 posti letto) ed il tavolo con 5 sedie. Da qui si accede ad un'ulteriore camera che dispone di letto ad una piazza e mezzo (2 posti letto), al bagno completo di doccia e lavatrice ed alla cucina dotata di forno elettrico e a microonde, frigorifero, stoviglie, posate, pentolame e tutto quanto occorrente per l'uso. L'appartamento è completamente climatizzato per essere utilizzato tutto l'anno. Gli ospiti possono usufruire gratuitamente della piscina (vengono riservati un ombrellone e due lettini), della rete wi-fi e del posto auto. La colazione non è inclusa. La biancheria e gli asciugamani non sono inclusi, il servizio è opzionale a pagamento. Se acquistato vengono forniti: biancheria da bagno per ciascun ospite (telo bagno e asciugamani), biancheria completa da letto e kit cortesia bagno (bagnoschiuma, saponetta, carta igienica).",
      "pictures" : {
         "picture1" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza3_1.jpg" ,
         "picture2" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza3_2.jpg" ,
         "picture3" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza3_3.jpg" ,
         "picture4" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza3_4.jpg" ,
         "picture5" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza3_5.jpg" ,
         "picture6" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza3_6.jpg" ,
         "picture7" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza3_7.jpg" ,
         "picture8" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza3_8.jpg" ,
      } ,
      "iconsName" : ["letto","TV","Cucina","Frigorifero","Forno elettrico","Microonde","Tavolo per 5","Lavatrice","Doccia","Phon","Condizionatore","Termosifoni","Armadio","Wifi","Piscina","Parcheggio","Sport","Giardino","Per famiglie","Fuga romantica"] ,
      "iconsLink" :[
        "https://www.tenutaricco.it/site/assets/img/icon/postiletto-64.png" , 
        "https://www.tenutaricco.it/site/assets/img/icon/tv-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/cucina-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/frigorifero-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/fornoelettrico-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/microonde-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/tavolo-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/lavatrice-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/doccia-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/phon-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/condizionatore-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/riscaldamento-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/armadio-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/wifi-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/piscina-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/parcheggio-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/sport-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/giardino-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/famiglia-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/cuore-64.png" , ] ,
    } ,

    {
      "id": 4,
      "title" : "Alloggio 4" ,
      "roomType" : "Casa vacanza con cucina" , 
      "bedNumber" : "4 posti letto" ,
      "img" : room4 ,
      "video" : "https://www.youtube.com/embed/znoWlCD6VHw" ,
      "description" : "L'alloggio, a cui si accede da una scala esterna, è situato al piano primo della struttura, ed è costituito da un soggiorno con cucina, una camera da letto, un disimpegno ed un bagno con doccia, per complessivi 30 metri quadrati e 4 posti letto. Nella camera principale si trovano un letto matrimoniale (2 posti letto) ed un letto singolo (1 posto letto). Nel soggiorno, invece, si trova un divano letto apribile (1 posto letto), un tavolo con 4 sedie ed una TV hd. L'alloggio è completamente climatizzato e può essere utilizzato tutto l'anno. Gli ospiti possono usufruire gratuitamente della piscina (vengono riservati un ombrellone e due lettini), della rete wi-fi e del posto auto. La colazione non è inclusa. La biancheria e gli asciugamani non sono inclusi, il servizio è opzionale a pagamento. Se acquistato vengono forniti: biancheria da bagno per ciascun ospite (telo bagno e asciugamani), biancheria completa da letto e kit cortesia bagno (bagnoschiuma, saponetta, carta igienica).",
      "pictures" : {
          "picture1" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza4_1.jpg" ,
          "picture2" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza4_2.jpg" ,
          "picture3" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza4_3.jpg" ,
          "picture4" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza4_4.jpg" ,
          "picture5" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza4_5.jpg" ,
          "picture6" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza4_6.jpg" ,
          "picture7" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza4_7.jpg" ,
          "picture8" : "https://www.tenutaricco.it/site/assets/img/portfolio/stanza4_8.jpg" ,
      } ,
      "iconsName" : ["letto","TV","Cucina","Frigorifero","Forno elettrico","Microonde","Tavolo per 5","Lavatrice","Doccia","Phon","Condizionatore","Termosifoni","Armadio","Wifi","Piscina","Parcheggio","Sport","Giardino","Per famiglie","Fuga romantica"] ,
      "iconsLink" :[
        "https://www.tenutaricco.it/site/assets/img/icon/postiletto-64.png" , 
        "https://www.tenutaricco.it/site/assets/img/icon/tv-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/cucina-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/frigorifero-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/fornoelettrico-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/microonde-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/tavolo-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/lavatrice-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/doccia-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/phon-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/condizionatore-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/riscaldamento-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/armadio-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/wifi-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/piscina-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/parcheggio-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/sport-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/giardino-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/famiglia-64.png" ,
        "https://www.tenutaricco.it/site/assets/img/icon/cuore-64.png" , ] ,
    } 
  ]
